# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 610)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setGeometry(QtCore.QRect(30, 460, 650, 50))
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_addRow = QtWidgets.QPushButton(self.gridWidget)
        self.btn_addRow.setObjectName("btn_addRow")
        self.gridLayout_3.addWidget(self.btn_addRow, 0, 0, 1, 1)
        self.btn_removeRow = QtWidgets.QPushButton(self.gridWidget)
        self.btn_removeRow.setObjectName("btn_removeRow")
        self.gridLayout_3.addWidget(self.btn_removeRow, 0, 2, 1, 1)
        self.btn_removeColumn = QtWidgets.QPushButton(self.gridWidget)
        self.btn_removeColumn.setObjectName("btn_removeColumn")
        self.gridLayout_3.addWidget(self.btn_removeColumn, 0, 3, 1, 1)
        self.btn_addColumn = QtWidgets.QPushButton(self.gridWidget)
        self.btn_addColumn.setObjectName("btn_addColumn")
        self.gridLayout_3.addWidget(self.btn_addColumn, 0, 1, 1, 1)
        self.btn_readCell = QtWidgets.QPushButton(self.gridWidget)
        self.btn_readCell.setObjectName("btn_readCell")
        self.gridLayout_3.addWidget(self.btn_readCell, 0, 4, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 690, 440))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.lbl_readCell = QtWidgets.QLabel(self.centralwidget)
        self.lbl_readCell.setGeometry(QtCore.QRect(350, 530, 350, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_readCell.setFont(font)
        self.lbl_readCell.setStyleSheet("QLabel#lbl_readCell{\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.lbl_readCell.setObjectName("lbl_readCell")
        self.lbl_text = QtWidgets.QLabel(self.centralwidget)
        self.lbl_text.setGeometry(QtCore.QRect(240, 530, 101, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_text.setFont(font)
        self.lbl_text.setObjectName("lbl_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_addRow.setText(_translate("MainWindow", "Add Row"))
        self.btn_removeRow.setText(_translate("MainWindow", "Remove Row"))
        self.btn_removeColumn.setText(_translate("MainWindow", "Remove Column"))
        self.btn_addColumn.setText(_translate("MainWindow", "Add Column"))
        self.btn_readCell.setText(_translate("MainWindow", "Read Cell"))
        self.lbl_readCell.setText(_translate("MainWindow", "Giá trị đọc được"))
        self.lbl_text.setText(_translate("MainWindow", "Giá trị ô: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
