# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 450)
        MainWindow.setMaximumSize(QtCore.QSize(550, 450))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("password.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_image = QtWidgets.QLabel(self.centralwidget)
        self.lbl_image.setGeometry(QtCore.QRect(240, 20, 70, 70))
        self.lbl_image.setText("")
        self.lbl_image.setPixmap(QtGui.QPixmap("user.png"))
        self.lbl_image.setScaledContents(True)
        self.lbl_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_image.setObjectName("lbl_image")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(125, 320, 300, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("QPushButton#btn_login{\n"
"    background-color: rgb(255,165,0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton#btn_login:hover {\n"
"    background-color: rgb(255, 140, 0);\n"
"}\n"
"\n"
"QPushButton#btn_login:pressed {\n"
"\n"
"}\n"
"")
        self.btn_login.setObjectName("btn_login")
        self.lbl_login = QtWidgets.QLabel(self.centralwidget)
        self.lbl_login.setGeometry(QtCore.QRect(205, 110, 140, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lbl_login.setFont(font)
        self.lbl_login.setStyleSheet("color: rgb(243, 156, 18);")
        self.lbl_login.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_login.setObjectName("lbl_login")
        self.lnEdit_acc = QtWidgets.QLineEdit(self.centralwidget)
        self.lnEdit_acc.setGeometry(QtCore.QRect(125, 190, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lnEdit_acc.setFont(font)
        self.lnEdit_acc.setStyleSheet("border: none;\n"
"border-bottom: 3px solid rgba(189, 195, 199, 255);\n"
"background-color: qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"\n"
"")
        self.lnEdit_acc.setObjectName("lnEdit_acc")
        self.lnEdit_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.lnEdit_pass.setGeometry(QtCore.QRect(125, 250, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lnEdit_pass.setFont(font)
        self.lnEdit_pass.setStyleSheet("border: none;\n"
"border-bottom: 3px solid rgba(189, 195, 199, 255);\n"
"background-color: qradialgradient(stop:1 rgba(255, 255, 255, 0));\n"
"")
        self.lnEdit_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lnEdit_pass.setObjectName("lnEdit_pass")
        self.lbl_accIcon = QtWidgets.QLabel(self.centralwidget)
        self.lbl_accIcon.setGeometry(QtCore.QRect(85, 190, 30, 30))
        self.lbl_accIcon.setText("")
        self.lbl_accIcon.setPixmap(QtGui.QPixmap("account.png"))
        self.lbl_accIcon.setScaledContents(True)
        self.lbl_accIcon.setObjectName("lbl_accIcon")
        self.lbl_passIcon = QtWidgets.QLabel(self.centralwidget)
        self.lbl_passIcon.setGeometry(QtCore.QRect(85, 250, 30, 30))
        self.lbl_passIcon.setText("")
        self.lbl_passIcon.setPixmap(QtGui.QPixmap("unlock.png"))
        self.lbl_passIcon.setScaledContents(True)
        self.lbl_passIcon.setObjectName("lbl_passIcon")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(125, 380, 300, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("QPushButton#btn_exit{\n"
"    background-color: rgb(169,169,169);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid rgba(169,169,169);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton#btn_exit:hover {\n"
"    background-color: rgb(128,128,128);\n"
"}\n"
"\n"
"QPushButton#btn_exit:pressed {\n"
"\n"
"}\n"
"")
        self.btn_exit.setObjectName("btn_exit")
        self.lbl_background = QtWidgets.QLabel(self.centralwidget)
        self.lbl_background.setGeometry(QtCore.QRect(10, 10, 530, 430))
        self.lbl_background.setStyleSheet("QLabel#lbl_background{\n"
"    background-color: rgba(105,105,105,200);\n"
"    border-radius: 20%;\n"
"}\n"
"\n"
"\n"
"")
        self.lbl_background.setText("")
        self.lbl_background.setScaledContents(True)
        self.lbl_background.setObjectName("lbl_background")
        self.lbl_background.raise_()
        self.lbl_image.raise_()
        self.btn_login.raise_()
        self.lbl_login.raise_()
        self.lnEdit_acc.raise_()
        self.lnEdit_pass.raise_()
        self.lbl_accIcon.raise_()
        self.lbl_passIcon.raise_()
        self.btn_exit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login Screen"))
        self.btn_login.setText(_translate("MainWindow", "Login"))
        self.lbl_login.setText(_translate("MainWindow", "Login"))
        self.lnEdit_acc.setPlaceholderText(_translate("MainWindow", "User name"))
        self.lnEdit_pass.setPlaceholderText(_translate("MainWindow", "Password"))
        self.btn_exit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
