# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 175)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.widget_5)
        self.widget_3.setStyleSheet("QWidget#widget_3{\n"
"    border: 1px solid;\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget_3)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_temperatureDisplay = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_temperatureDisplay.setFont(font)
        self.lbl_temperatureDisplay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_temperatureDisplay.setObjectName("lbl_temperatureDisplay")
        self.horizontalLayout_2.addWidget(self.lbl_temperatureDisplay)
        self.lbl_temperatureValue = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_temperatureValue.setFont(font)
        self.lbl_temperatureValue.setObjectName("lbl_temperatureValue")
        self.horizontalLayout_2.addWidget(self.lbl_temperatureValue)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_humidityDisplay = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_humidityDisplay.setFont(font)
        self.lbl_humidityDisplay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_humidityDisplay.setObjectName("lbl_humidityDisplay")
        self.horizontalLayout.addWidget(self.lbl_humidityDisplay)
        self.lbl_humidityValue = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_humidityValue.setFont(font)
        self.lbl_humidityValue.setObjectName("lbl_humidityValue")
        self.horizontalLayout.addWidget(self.lbl_humidityValue)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout_3.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_5)
        self.widget_4.setStyleSheet("QWidget#widget_4{\n"
"    border: 1px solid;\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_ledDisplay = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_ledDisplay.setFont(font)
        self.lbl_ledDisplay.setObjectName("lbl_ledDisplay")
        self.verticalLayout_2.addWidget(self.lbl_ledDisplay)
        self.btn_led = QtWidgets.QPushButton(self.widget_4)
        self.btn_led.setObjectName("btn_led")
        self.verticalLayout_2.addWidget(self.btn_led)
        self.horizontalLayout_3.addWidget(self.widget_4)
        self.gridLayout.addWidget(self.widget_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_temperatureDisplay.setText(_translate("MainWindow", "Nhiệt độ:"))
        self.lbl_temperatureValue.setText(_translate("MainWindow", "None *C"))
        self.lbl_humidityDisplay.setText(_translate("MainWindow", "Độ ẩm:"))
        self.lbl_humidityValue.setText(_translate("MainWindow", "None %"))
        self.lbl_ledDisplay.setText(_translate("MainWindow", "Led Control"))
        self.btn_led.setText(_translate("MainWindow", "ON"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
