# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setEnabled(True)
        self.btn_start.setGeometry(QtCore.QRect(50, 350, 100, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_start.setFont(font)
        self.btn_start.setObjectName("btn_start")
        self.btn_copy = QtWidgets.QPushButton(self.centralwidget)
        self.btn_copy.setEnabled(True)
        self.btn_copy.setGeometry(QtCore.QRect(250, 350, 100, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_copy.setFont(font)
        self.btn_copy.setObjectName("btn_copy")
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setEnabled(True)
        self.btn_stop.setGeometry(QtCore.QRect(450, 350, 100, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_stop.setFont(font)
        self.btn_stop.setObjectName("btn_stop")
        self.lbl_display = QtWidgets.QLabel(self.centralwidget)
        self.lbl_display.setGeometry(QtCore.QRect(50, 80, 500, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_display.setFont(font)
        self.lbl_display.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_display.setLineWidth(2)
        self.lbl_display.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_display.setObjectName("lbl_display")
        self.txtEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtEdit.setGeometry(QtCore.QRect(50, 180, 500, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtEdit.setFont(font)
        self.txtEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.txtEdit.setObjectName("txtEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_copy.setText(_translate("MainWindow", "Copy"))
        self.btn_stop.setText(_translate("MainWindow", "Stop"))
        self.lbl_display.setText(_translate("MainWindow", "Text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
